# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45)),
                ('business_title', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('extension', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=14)),
                ('call_date_time', models.DateTimeField()),
                ('duration_in_seconds', models.IntegerField()),
                ('inbound', models.BooleanField()),
            ],
        ),
    ]
